package isf.UTILS;


public interface ExcelConstants
{

    public static final String RFHB = "\u2767";
    public static final String TC1TDT1 = "[Text Descriptive Title:]";
    public static final String TC1MTPN2 = "[Main Text or Publication Number:]";
    public static final String TC1ATT3 = "[Alternate Text Title:]";
    public static final String TC2TD1 = "[Text Description:]";
    public static final String TC2TPNN2 = "[Text or Publication Number Note:]";
    public static final String TC2ED3 = " [Excavation Description:]";
    public static final String TC2M4 = "[Medium:]";
    public static final String TC2SN5 = "[Script Note:]";
    public static final String TC2POD6 = "[Physical Object Description:]";
    public static final String TC2PON7 = "[Physical Object Note:]";
    public static final String TC3KOP1 = "[Keywords or Phrases:]";
    public static final String TC4LOO = "[Location of Original:]";
    public static final String TC4IFS1 = "[ISF Find Site:]";
    public static final String TC4AS2 = "[Ancient Structure:]";
    public static final String TC4R3 = "[Region:]";
    public static final String TC4GCN4 = "[Geographical Coverage Note:]";
    public static final String TC4ACOL5 = "[Ancient City or Location:]";
    public static final String TC5MCL = "[Modern City or Location:]";
    public static final String TC6MC = "[Modern Country:]";
    public static final String TC7NTP1 = "[Named Time Period:]";
    public static final String TC7DIN2 = "[Date of Inscription Note:]";
    public static final String TC7RTL3 = "[Relevant Time Line:]";
    public static final String TC10P = "University of Southern California. Libraries";
    public static final String TC12TIC1 = "[Type of Item Catalogued:]";
    public static final String TC12TUG2 = "[Text/Uninscribed/Glyptic:]";
    public static final String TC14LN1 = "[Language Note:]";
    public static final String TC15IATN1 = "[ISF Assigned Text Number:]";
    public static final String TC15MAN2 = "[Museum Accession Number:]";
    public static final String TC15EN3 = "[Excavation Number:]";
    public static final String TC16POC = "InscriptiFact: an image database of inscriptions and artifacts";
    public static final String TC18IPOC1 = "[Is Part Of Corpus<N>:]";
    public static final String TC18IPOCC2 = "[Is Part Of Corpus<N> Category:]";
    public static final String TC18IPOCSC3 = "[Is Part Of Corpus<N> Sub-Category:]";
    public static final String TC19TD1 = "[Text Division:]";
    public static final String TC19TDD2 = "[Text Division Description:]";
    public static final String TC20RPO1 = "[Rights Physical Object:]";
    public static final String TC21LOO1 = "[Location of Original:]";
    public static final String PUBLISHER = "University of Southern California. Libraries";
    public static final String COLLECTION = "InscriptiFact: an image database of inscriptions and artifacts";
    public static final String PC1PDT1 = "[Photo Descriptive Title:]";
    public static final String PC2DOTN1 = "[Digital Object Type Note:]";
    public static final String PC2PD2 = "[Photograph Description:]";
    public static final String PC2ATR3 = "[Ancient Text Represented:]";
    public static final String PC8P1 = "[Photographer:]";
    public static final String PC8DES2 = "[Digitization Equipment Specs:]";
    public static final String PC9C1 = "[Collaborator:]";
    public static final String PC11DOP1 = "[Date of Photograph:]";
    public static final String PC11DODC2 = "[Date of Digital Conversion:]";
    public static final String PC13AFR1 = "[Archival File Resolution:]";
    public static final String PC13AFS2 = "[Archival File Size:]";
    public static final String PC13DOF3 = "[Digital Object Format:]";
    public static final String PC13FTC4 = "[Film Type Code:]";
    public static final String PC13MC5 = "[Magnification Code:]";
    public static final String PC13PD6 = "[Photo Dimensions:]";
    public static final String PC15IDOIN1 = "[ISF Digital Object Identification Number:]";
    public static final String PC15PIN2 = "[Photograph Identification Number:]";
    public static final String PC15PMAN3 = "[Photo Museum Accession Number Note:]";
    public static final String PC15PTOPNN4 = "[Photo Text or Publication Number Note:]";
    public static final String PC18IPOWSRP1 = "[Is Part of WSR Project:]";
    public static final String PC20RDO1 = "[Rights Digital Object:]";
    public static final String PC20RPO2 = "[Rights Photographic Object:]";
    public static final String PC20RPO3 = "[Rights Physical Object:]";
    public static final String PC20RPP4 = "[Rights Publication Permission:]";
}
